### ISSUE TITLE
Suggester - affichage d'un "carré"

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/stromae-dsfr#102]
En visu StromaeDSFR la suppression du suggester est sous forme de carré : 
![image](https://github.com/user-attachments/assets/b309a879-e952-4e9e-b77b-c252ae939d8b)

Alors que sur le storybook dsfr tout semble ok ?

**Comment by laurentC35** [comment]
On dirait qu'il manque une icone

**Comment by ddecrulle** [comment]
Problème de cache du fichier `/dsfr/utility/icons/icons.min.css`. Ce fichier et 'patché' par [@codegouv/react-dsfr](https://react-dsfr.codegouv.studio/icons), mais son nom ne change pas donc il n'est pas retéléchargé par les navigateurs quand on rajoute un icon. Je regarde pour améliorer le comportement de react-dsfr
