### ISSUE TITLE
Modale de reprise affichée à tort

### ISSUE THREAD

**Issue by JulienCarmona** [InseeFr/stromae-dsfr#132]
### Env
PROD Concevoir

### Sample
UE 849-CAWI-1

### Bug 
Aller sur le questionnaire.
La modale s'affiche à tort.
![Image](https://github.com/user-attachments/assets/7419939e-99ed-4b6c-879b-ea4ab8b84f26)

alors que l'UE a pour état
```json
{
	"stateData": {
		"state": "VALIDATED",
		"date": 1728055144812,
		"currentPage": "endPage"
	}
}
```

### Comportement attendu
Quand on a un questionnaire dans l'état `VALIDATED`, on ne devrait pas afficher la modale suivante.

**Comment by QRuhier** [comment]
Attention à l'état correspondant qui peut aussi être `EXTRACTED`. Plutôt s'appuyer sur la currentPage (= endpage)

**Comment by JulienCarmona** [comment]
Validé en QF : ✅
