### ISSUE TITLE
Survey's last page message don't fit displayed Timestamp after Platine extraction

### ISSUE THREAD

**Issue by JulienCarmona** [InseeFr/stromae-dsfr#133]
### Env
PROD Collecter

### Survey
Any

### Bug Descirption

> quand on consulte le questionnaire d'une UE répondante, la date d'envoi de son questionnaire varie entre le moment où elle vient de l'envoyer (on voit alors la vraie date d'expédition par l'entreprise) et le moment où il y a eu l'extraction Platine (ond voit alors la date d'extraction depuis Platine, vers 6h) comme le montre les copies d’écran ci-dessous.
> ==> une fois l'extraction faite, on ne voit plus à quelle heure l'UE a expédié son questionnaire, d'autant qu'on n'a pas accès à la preuve de dépôt quand on clique dessus 

### Screenshot
![image](https://github.com/user-attachments/assets/4a06996d-8ce9-4d38-9add-ee698c7eae35)
![image](https://github.com/user-attachments/assets/da2b3239-67cd-4db5-a4fc-bbb729e96065)

### Comportement attendu
Avoir une heure qui correspond à l'état

### Solutions

1. ~Changer la stratégie du batch pour ne plus update l'état du questionnaire lors de l'extraction~
- https://github.com/InseeFr/stromae-dsfr/issues/133#issuecomment-2399272922
2. Changer le message suivant l'état du questionnaire

**Comment by JulienCarmona** [comment]
@AnneHuSKa Il faudrait déterminer l'autre message que l'on souhaite afficher dès que le batch d'extraction Platine soit passé.
Je ne sais pas trop à quel point il faut être proche de la "réalité technique" ou non.

Est-ce que tu as une idée ?

**Comment by AnneHuSKa** [comment]
@JulienCarmona j'ai des idées pas forcément top : tu veux poser la question à Collecter ? Ce sont eux qui seront les plus concernés non  ?

**Comment by laurentC35** [comment]
Vu avec Collecter, dans un premier temps on va afficher:
- Si `VALIDATED` on change rien
- Si `TOEXTRACT` ou `EXTRACTED`:
  - retirer la date, le message devient: `Vos réponses ont bien été envoyées.`

**Comment by JulienCarmona** [comment]
Testé en visu recette avec un questionnaire tiré de PE dans l'état `VALIDATED` 
 ```json
{
  "stateData": {
    "state": "VALIDATED",
    "date": 1730217107584,
    "currentPage": "endPage"
  }
}
```
![image](https://github.com/user-attachments/assets/00dd37f0-64e0-4fe6-b70a-9d93f035aadf)

Avec les états `TOEXTRACT` et `EXTRACTED`
 ```json
{
  "stateData": {
    "state": "TOEXTRACT",
    "date": 1730217107584,
    "currentPage": "endPage"
  }
}
```
![image](https://github.com/user-attachments/assets/adf58272-c9d6-427f-8d7d-883379ff39e9)
