### ISSUE TITLE
'date of validation' displayed is updated when coming back

### ISSUE THREAD

**Issue by QRuhier** [InseeFr/stromae-dsfr#135]
### Bug Descirption

When being on the end page, we display the 'date of validation'.
But when disconnecting and coming back, the date is updated

**Comment by QRuhier** [comment]
- quite related to https://github.com/InseeFr/stromae-dsfr/issues/133

**Comment by QRuhier** [comment]
It also updated from state 'extracted' to 'validated', leading potentially to multiple extractions by Platine

**Comment by JulienCarmona** [comment]
Testé en QF ✅ 
Une déconnexion ne met plus à jour la date affichée sur la dernière page.

Par contre, il y a toujours un bug sur l'affichage du premier horaire qui affiche n'imp

Je fais un nouveau ticket pour ça et je clos celui-là
