### ISSUE TITLE
Créer des évènements de tracking niveau questionnaire

### ISSUE THREAD

**Issue by laurentC35** [InseeFr/stromae-dsfr#139]
# User Story

__En tant que__ : équipe collecter/traiter
__Je veux__ : que des évènements soient crées lorsque l’utilisateur déclenche une action (en mode collecter)
- changement de page
- changement de valeur (lunatic event)
- déclenchement de controles / erreurs
- navigation (clic bouton / lien externe)

Avec les valeurs :
-  date ISO 8601
-  User-Agent
- idSU
- (opt) lunatic

__Afin de__ : les recevoir via API (Queen-Back-Office)

# Definition of Done:
- des tests unitaires avec un outil de simulation de comportement répondant
- vérifier que les évènement décrits ci-dessus sont bien récupérés par l'IHM
- monté.e en compétence sur les tests

# A adapter:
- les liens statiques de pieds de page sont à modifier pour ouvrir un nouvel onglet (au lieu de changer la page courante)

# Scenarios de test
- [ ] Ouvrir un questionnaire, cliquer sur les liens statiques de pieds de page. Vérifier qu'un évènement est bien capturé avec l'information du lien/navigation.

**Comment by JulienCarmona** [comment]
> [!WARNING]
> Avec les paradata, on a du mettre à jour la manière de build Lunatic et Lunatic-DSFR pour faire passer les tests.
> Tout est ok maintenant niv test auto mais on est pas à l’abri d’une regression. Il faudra donc bien recetter lunatic/DSFR pour la prochaine release.
