### ISSUE TITLE
Wrong Date of validation just after sending answers

### ISSUE THREAD

**Issue by JulienCarmona** [InseeFr/stromae-dsfr#151]
Create after validating 
- https://github.com/InseeFr/stromae-dsfr/issues/135

## Bug
When validating answers on Public Enemy, the date displayed just after that is wrong
![image](https://github.com/user-attachments/assets/8aaee9b5-aa27-4356-9ba0-906ae837d076)
But when refreshing the page we have the right time
![image](https://github.com/user-attachments/assets/7fe4274c-2575-488b-8f00-4703bd7a2947)

## Steps to reproduce

1. Ouvrir un formulaire pour la première fois
2. Commencer à répondre
3. Le fermer (par exemple à 10:10)
4. Le réouvrir à une date ultérieure (par exemple à 10:15)
5. Valider le questionnaire
6. La date affichée est 10:10

**Comment by laurentC35** [comment]
@JulienCarmona Nous n'arrivons pas reproduire le bug, peux-tu décrire la marche à suivre pour le reproduire.
Merci 😉

**Comment by laurentC35** [comment]
Pour réproduire:

1. Ouvrir un formulaire pour la première fois
2. Commencer à répondre
3. Le fermer (par exemple à 10:10)
4. Le réouvrir à une date ultérieure (par exemple à 10:15)
5. Valider le questionnaire
6. La date affichée est 10:10

**Comment by JulienCarmona** [comment]
Valider en QF : ✅
