### ISSUE TITLE
Paradata - allow to update batch parameters in deployment

### ISSUE THREAD

**Issue by chloe-renaud** [InseeFr/stromae-dsfr#172]
As an IT guy,
I want to update batch parameters used for paradata (currently set by default as "send every 1min or 10 events") whenever I want through deployment variables,
So that I can adapt to my server capability without having to update the coding base which I don't necessarily have the ability to udpate.

**Comment by lailabent** [comment]
Migrée vers tuleap https://tuleap.insee.fr/plugins/tracker/?aid=9910
