### ISSUE TITLE
DatePicker - persistance des données format Year et Month Year

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/stromae-dsfr#85]
Pb de persistance des données dans Year et MonthYear.
Lorsqu'une donnée a été saisie, on ne peut plus la modifier. La première donnée saisie est conservée.
[Issue85.json](https://github.com/user-attachments/files/16030810/Issue85.json)

=> pas de pb sur Lunatic 3.0
=> pb constaté sur Storybook Dsfr

**Comment by QRuhier** [comment]
cf. https://github.com/InseeFr/Lunatic-DSFR/issues/186
