### ISSUE TITLE
Footer - informations

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/stromae-dsfr#88]
Texte de présentation - optionnel
- [ ] ne rien mettre

4 liens de références de l'écosystème institutionnel (seront validés le 10.07): 
- [ ] Cnis.fr
- [ ] Système statistique européen : https://ec.europa.eu/eurostat/fr/web/main/home ?
- [ ] Insee : https://www.insee.fr/fr/information/1302230 
- [ ] Services publics + : https://www.plus.transformation.gouv.fr/

**Comment by laurentC35** [comment]
En attente de retour du bureau si on peut "personnaliser le DSFR"

**Comment by AnneHuSKa** [comment]
@ddecrulle : texte de présentation à mettre à vide dans la version qui sera proposée en collecte aout 2024.
Sera enrichi plus tard
