### ISSUE TITLE
Page de fin - transmission du questionnaire impossible ?

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/stromae-dsfr#98]
En intégration, arrivé à la dernière page avant l’envoi du questionnaire, l’enquêté doit cliquer sur « continuer ». Le passage à la page d’envoi est très très très long. Si l’enquêté clique de nouveau sur « continuer », l’application plante.
Pour envoyer son questionnaire, l’enquêté doit alors repasser tout son questionnaire, question par question. Dans certains cas, envoie sur une page 
![image](https://github.com/InseeFr/stromae-dsfr/assets/71011059/8a13a1cf-5919-4b37-a696-03d24abe88b3)

Testé : 
DV2 :  enquetes.developpement2. 
ID         8ZJLV6T
MDP    *********
Le questionnaire avait planté à la dernière page.
A la reconnexion, tout a été sauvegardé mais on n'a pas la modale "revenir à la dernière page accédée" comme si elle n'existait pas : mais tout le questionnaire est rempli.

**Comment by ddecrulle** [comment]
Il y a un souci dans le questionnaire/et ou Lunatic. Ce n'est pas lié à stromae-dsfr. 

Tout est ok à la page 43. Le problème apparait au passage de la page 44. 

Le composant est le suivant : 

```json
{
			"id": "question-ltn4dw33",
			"page": "44",
			"label": {
				"type": "VTL|MD",
				"value": "\"NE PAS POSER LA QUESTION - Quelle est l'heure de fin de l'entretien ?\r\n\""
			},
			"components": [
				...
			],
			"declarations": [
				...
			],
			"componentType": "Question",
			"conditionFilter": {
				"type": "VTL",
				"value": "(SABIANE12=\"2\")"
			}
		}
```

`SABIANE12` est une variable externe. Dans l'exemple présenté, sa valeur est :  `"1"`. Si je modifie cette valeur par un 2 je n'ai aucun souci.

**Comment by AnneHuSKa** [comment]
Merci @ddecrulle
